### ISSUE TITLE
`gdrive_download.py` cannot download data from Google Drive

### ISSUE THREAD

**Issue by jimmy-sonny** [Cisco-Talos/binary_function_similarity#15]
When running `python3 ../gdrive_download.py --binaries`, I get the following error:
```
Downloading Dataset-1.zip ...
Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=1QpRgVJZTM52bfB6PvCKwVnmkKdHenUai
...
```

**Comment by keenlooks** [comment]
I'm having the same issue. Find any fix?

**Comment by jimmy-sonny** [comment]
Upgrading gdown from `4.4.0` to `4.6.0` works for me, but I've not investigated the root cause of the problem yet.

Instructions:
```
cd Binaries
source ../env/bin/activate
pip install gdown==4.6.0
```

**Comment by jimmy-sonny** [comment]
@keenlooks do you have any feedback? Thank you

**Comment by m2kar** [comment]
> Upgrading gdown from `4.4.0` to `4.6.0` works for me, but I've not investigated the root cause of the problem yet.
> 
> Instructions:
> 
> ```
> cd Binaries
> source ../env/bin/activate
> pip install gdown==4.6.0
> ```

This method work for me too. May be the google driver download page for big file and normal file is different, but the old version of `gdown` didn't handle this different.

**Comment by jimmy-sonny** [comment]
From my tests, changing `gdown` from version `4.5.3` to `4.5.4` does fix the issue. This seems to be [related](https://github.com/wkentaro/gdown/compare/v4.5.3...v4.5.4) to a minor change in the Google Drive URL format.
