### ISSUE TITLE
\IDA_scripts\IDA_flowchart\IDA_flowchart.py: module 'idc' has no attribute 'Exit'

### ISSUE THREAD

**Issue by XX-Official** [Cisco-Talos/binary_function_similarity#17]
when running the IDA FlowChart plugin over the IDBs of the Dataset-Vulnerability, an error occured:
`
.../binary_function_similarity-main\IDA_scripts\IDA_flowchart\IDA_flowchart.py: module 'idc' has no attribute 'Exit'
Traceback (most recent call last):
  File "...\IDA_Pro_v7.5\python\3\ida_idaapi.py", line 616, in IDAPython_ExecScript
    exec(code, g)
  File ".../binary_function_similarity-main/binary_function_similarity-main/IDA_scripts/IDA_flowchart/IDA_flowchart.py", line 197, in <module>
    idc.Exit(0)
AttributeError: module 'idc' has no attribute 'Exit'
`
How to solve this problem?

**Comment by jimmy-sonny** [comment]
Hi @XX-Official,

thank you for opening this issue.

The IDAPro plugins that we have released have been developed for `IDA Pro 7.3 Linux x86_64` and `Python 2` (more info [here](https://github.com/Cisco-Talos/binary_function_similarity/tree/main/IDA_scripts#the-ida-pro-plugins)). From the exception logs, I see that you're using IDAPro 7.5. 

Looking at the IDAPro guide (https://hex-rays.com/products/ida/support/ida74_idapython_no_bc695_porting_guide.shtml), `idc.Exit` should be changed to `ida_pro.qexit`.

This is also related to: https://github.com/Cisco-Talos/binary_function_similarity/pull/9

**Comment by XX-Official** [comment]
> 

The problem has been resolved. Thank you very much！

**Comment by XX-Official** [comment]
The problem has been resolved. Thank you very much！
