### ISSUE TITLE
How to use free version of IDA with this project?

### ISSUE THREAD

**Issue by hoosierEE** [Cisco-Talos/binary_function_similarity#20]
Hi, I'm interested in running these experiments using the free version of IDA Pro, which only supports x86.
What changes, if any, do you suggest so I can train the Asm2Vec model or others?

**Comment by jimmy-sonny** [comment]
As far as I know, the IDA Freeware version doesn't allow you to execute Python scripts, but I'll let you double check this. If so, you cannot leverage all the IDA python [scripts](https://github.com/Cisco-Talos/binary_function_similarity/tree/main/IDA_scripts) that we have written. Probably the IDA Freeware version allows to run IDC scripts and in such a case you could try to convert the Python code in C.

Apart from that, I do see two main alternatives:
a) Use python-idb (https://github.com/williballenthin/python-idb), a library for accessing the contents of IDA Pro databases. However, be aware that 1) not all the APIs that we use are implemented 2) the results may differ from what IDA Pro does.
b) Replace IDA Pro with one of the free alternatives (e.g., [Ghidra](https://ghidra-sre.org/) or [radare2](https://github.com/radareorg/radare2)), however this would require to rewrite all the scripts for the new framework of choice.

The Asm2vec model requires 2 IDA scripts: 1) [IDA flowchart](https://github.com/Cisco-Talos/binary_function_similarity/tree/main/IDA_scripts/IDA_flowchart) for the dataset creation and 2) IDA [ACFG-disasm](https://github.com/Cisco-Talos/binary_function_similarity/tree/main/IDA_scripts/IDA_acfg_disasm) for the CFG creation and basic-blocks disassembly. The core of the two scripts is the IDA's FlowChart API that is used to determine the basic blocks. On the other hand, the disassembly is done via [capstone](https://github.com/capstone-engine/capstone).
