### ISSUE TITLE
GGSNN-GMN test on Dataset-1

### ISSUE THREAD

**Issue by XX-Official** [Cisco-Talos/binary_function_similarity#26]
When I  run the training on the Dataset-1 for the GMN model and run Dataset-1 testing， I found the values of column `sim` in  result csv are negative.  How to solve the problem?

[pos_rank_testing_Dataset-1_sim.csv](https://github.com/Cisco-Talos/binary_function_similarity/files/11430715/pos_rank_testing_Dataset-1_sim.csv)

**Comment by jimmy-sonny** [comment]
Hi @XX-Official
