### ISSUE TITLE
Why not limit the compilation options for negative pairs?

### ISSUE THREAD

**Issue by eemario** [Cisco-Talos/binary_function_similarity#27]
Thank you for releasing your source code!

I've noticed that when selecting negative function pairs for different tasks (`create_similarity_pairs` and `create_similarity_pairs_random_version` in https://github.com/Cisco-Talos/binary_function_similarity/blob/main/DBs/Dataset-1/Dataset-1%20creation.ipynb), the only constraint is that the function names are different.
```
idx_list_neg = df_input[df_input["func_name"] != fname].index
...
idx_right_n = random.choice(idx_list_neg)
```
or
```
idx_right_n = random.randint(0, df_input.shape[0] - 1)
if df_input.iloc[idx_right_n]["func_name"] == fname:
    continue
```

In other words, all negative pairs are from "XM" task. Why shouldn't we set the constraints on negative pairs like we do to the positive ones(`idx_list_pos = df_libfunc[np.logical_and.reduce(constraints)].index`)? Or have I misunderstood the code?

**Comment by jimmy-sonny** [comment]
Hi @eemario

Thank you for asking, this is an interesting question.

Your interpretation of the code is correct: the only constraint used in the selection of negative functions is that function names are different.

There is no unique way to define how negative pairs are constructed - also I don't think there is a "correct" or a "wrong" way. As we mentioned in the paper, "pair selection" is a source of confusion in the existing literature although it plays a crucial role in the evaluation. However, as long as the experiments and comparison are consistent, I don't see any major issue.

Using the same criteria for the negative pairs selection allows us to compare the metrics from different tests and have an estimation of which configuration is more challenging.
