### ISSUE TITLE
How to get the input json file  with the selected functions for IDA ACFG disasm?

### ISSUE THREAD

**Issue by Hwwg** [Cisco-Talos/binary_function_similarity#28]
Hi, I would like to know how to generate the input JSON file mentioned in IDA ACFG disasm：

Input: a JSON file with the selected functions (-j) and the name of a folder in output (-o).

**Comment by jimmy-sonny** [comment]
Hi @Hwwg

for Dataset-1 you can check the last cell of this notebook: https://github.com/Cisco-Talos/binary_function_similarity/blob/main/DBs/Dataset-1/Dataset-1%20creation.ipynb
