### ISSUE TITLE
Wrong IDB path in json

### ISSUE THREAD

**Issue by patacca** [Cisco-Talos/binary_function_similarity#3]
I've noticed that in the json files (like `DBs/Dataset-1/features/testing/selected_testing_Dataset-1.json`) the path of the IDA exported database is different from the one that is obtained after running `IDA_Scripts/generate_idbs.py`

Running `python generate_idbs.py --db1` generates all the IDBs inside `IDBs/Dataset-1/` while inside `selected_testing_Dataset-1.json` the expected path is `IDBs/Dataset-1/{component}/` where component is one of openssl, nmap, curl, z3, clamav, curl, unrar, zlib

**Comment by jimmy-sonny** [comment]
What you have noticed is correct and thanks for opening this issue.

For Dataset-1 we organized the IDBs in sub directories, however this is not reflected in the `generate_idbs.py` script which only covers the "general case" where all the IDBs are saved in the same folder.
