### ISSUE TITLE
About idat64 commad

### ISSUE THREAD

**Issue by yanyou426** [Cisco-Talos/binary_function_similarity#32]
Hello. I noticed that when you processed with idapro, you used the idat64 command for both 32 or 64 bit binary to process it, generating files with .i64 extension, is this ok? don't you have to process it with the idat command for 32 bit?

**Comment by jimmy-sonny** [comment]
Hi @yanyou426,

From my understanding (and experience), `idat64` can process both 32 and 64 bit binaries, while `idat` can only process 32 bit binaries. In our experiments we only used `idat64` and `.i64` files to simplify the workflow. However, there is an exception: codeCMR [1] uses the hex-rays decompiler and in that case "only 32-bit code can be analyzed with ida32" and "only 64-bit code can be analyzed with ida64" [2].

You can find some information on the IDB format at this link: https://github.com/nlitsme/idbutil/blob/master/IDB-FORMAT.md

[1] https://github.com/Cisco-Talos/binary_function_similarity/blob/main/Models/CodeCMR/IDA_CodeCMR/cli_codeCMR.py#L91C2-L91C2
[2] https://www.hex-rays.com/products/decompiler/manual/limit.shtml

**Comment by wideglide** [comment]
@yanyou426, @jimmy-sonny 

If you are on the latest IDA release, ida32 is now considered deprecated.  From the release notes
https://www.hex-rays.com/products/ida/news/8_3/

> We have further improved IDA64 so that it can be a complete replacement for the legacy 32-bit IDA in all situations. To ease the migration, we implemented a feature to convert the legacy .idb databases to .i64 ones (codenamed CVT64).

And

> The 32-bit IDA is now considered deprecated and will likely go away at some point.

I think the decompiler limitations page is not updated?
