### ISSUE TITLE
Cannot restore GMN model

### ISSUE THREAD

**Issue by roxanecohen** [Cisco-Talos/binary_function_similarity#61]
Hello, 
Thank you for the amazing work you did. I'm trying to load the GMN model but I cannot do it due to an internal error:
```
2024-10-17 15:05:49.697589: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key graph-matching-net/graph-prop-0/gru/bh not found in checkpoint
Traceback (most recent call last):
  File "/home/lamsade/rcohen/GMN_new/venv2/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/lamsade/rcohen/GMN_new/venv2/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/lamsade/rcohen/GMN_new/venv2/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key graph-matching-net/graph-prop-0/gru/bh not found in checkpoint
	 [[{{node save/RestoreV2}}]]
```
It is possible that the model includes some mistakes or was not properly saved ? I'm using the _restore_model function just like you did. 
Thank you very much for you answer,

**Comment by jimmy-sonny** [comment]
Hi @rc-94, thank you for reporting this issue.

Can you please share the script you've used, and what is the checkpoint to load?

Thank you.

**Comment by roxanecohen** [comment]
Hi, 
Thank you very much for your reply. I'm actually using the method ```_restore_model``` from the class GNNModel of the core/gnn_model.py python file. It uses the ```checkpoint_dir``` key of the config file. In my case, this checkpoint dir is set to ```model_checkpoint_GGSNN_pair/```. This directory contains the files available in the corresponding checkpoint folder for GMN (checkpoint, graph-embedding-pair-40000.data-00000-of-00001, graph-embedding-pair-40000.index, graph-embedding-pair-40000.meta). Inside the method, the latest_checkpoint is loaded and in my case, it corresponds to the file ```model_checkpoint_GGSNN_pair/graph-embedding-pair-40000```

**Comment by jimmy-sonny** [comment]
Hi @rc-94, `gnn.py` implements two model variants: `GGSNN` (`--model_type embedding`) and `GMN` (`--model_type matching`). The two models implement different neural network architectures, and the checkpoints are also different. Can you please verify that you are loading the correct checkpoint for the corresponding selected model?

**Comment by roxanecohen** [comment]
Hello, 
Thank you ! It was indeed part of the problem. I was trying to load the ```matching``` model type with the available checkpoint but with ```embedding```, it works. Still, I'm not sure to understand where the checkpoints for the ```matching``` models are ?

Apart from that, I encountered some error when dealing with function with a single basic block and no edges. To fix the issue, I replaced the 
```
    if row_str == "" \
            or col_str == "" \
            or data_str == "":
        return np.identity(n_col)
```` 
by 
```
    if row_str == "" \
            or col_str == "" \
            or data_str == "":
        return np.identity(n_row)
```` 
It works with little adaptation, but I'm not sure it is a good fixup. Have you ever encountered such problem ? 
Thank you very much again

**Comment by jimmy-sonny** [comment]
Hi @rc-94, 

As you have correctly noticed, we have only uploaded the checkpoint of the GGSNN (embedding) model: for each neural network architecture there are different combinations of features and training options, and for practical reasons we have only uploaded a few checkpoints as examples.

You should be able to quickly train the model variant of interest - you can find the details in Table 8 of the [paper](https://www.usenix.org/system/files/sec22fall_marcelli.pdf).
In the case of the GMN (matching) model, it has been trained for 16 epochs using a batch size of 20. The other parameters are the same as in the [`config.py`](https://github.com/Cisco-Talos/binary_function_similarity/blob/main/Models/GGSNN-GMN/NeuralNetwork/core/config.py) file.

Regarding the function with **a single basic block and no edges**, in our research, we have only considered functions that have at least five basic blocks - this is to maintain compatibility with previous research on the topic. Both GGSNN and GMN are graph-based approaches, and they are very limited in efficacy when working with graphs that have a single node.

**Comment by roxanecohen** [comment]
Hello, 

Ok, it seems clear to me now. Thank you again for your help !
